FROM mcr.microsoft.com/mssql/server
# Create work directory
RUN mkdir -p /usr/work
WORKDIR /usr/work
# Copy all scripts INTO ONET.dbo.working directory
COPY ./scripts /usr/work/
# COPY ./scripts/import-data.sh /usr/work/import-data.sh
# COPY ./db_25_3_mssql /usr/work/db_25_3_mssql
EXPOSE 1433
COPY ./backups/ONET_25_3.bak /usr/work/backups/ONET_25_3.bak
COPY ./backups/RESTORE.sql /usr/work/backups/RESTORE.sql
COPY ./backups/RESTORE.sql /usr/work/backups/00_KEYS.sql
# COPY ./db_25_2_mssql/00_KEYS.sql /usr/work/00_KEYS.sql
# USER root
# # Grant permissions for the import-data script to be executable
USER root
RUN chmod +x /usr/work/import-data.sh
RUN chmod +x /usr/work/entrypoint.sh
# CMD /bin/sh /usr/work/entrypoint.sh
# ENTRYPOINT [ "/usr/work/entrypoint.sh" ]
# CMD /bin/sh /usr/work/import-data.sh
USER mssql
CMD /bin/bash /usr/work/entrypoint.sh